image:
  name: alpine/helm:3.7.2
  entrypoint: ["/bin/sh", "-c"]

stages:
  - init
  - package
  - upload

dependencies:
  stage: init
  script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm dependencies build
  only:
    variables:
      - $CI_COMMIT_TAG
  artifacts:
    paths:
      - charts/

package:
  stage: package
  script:
    - helm package .
  only:
    variables:
      - $CI_COMMIT_TAG
  artifacts:
    paths:
      - stream-*.tgz

upload:
  stage: upload
  script:
    - apk add curl
    - PACKAGE="$(find . -type f -name 'stream-*.tgz' -maxdepth 1 | head -n 1)"
    - curl -F file=@$PACKAGE --user "$NEXUS_USERNAME:$NEXUS_PASSWORD" https://repo.evertrust.io/service/rest/v1/components?repository=charts
  only:
    variables:
      - $CI_COMMIT_TAG
