apiVersion: v2
name: stream
description: EverTrust Stream Helm chart
type: application
version: 2.0.0
appVersion: "2.1.4"
icon: https://evertrust.io/media/logo-stream-blue.png
home: https://evertrust.io
sources:
  - https://github.com/evertrust/stream-helm
dependencies:
  - name: common
    version: 2.30.0
    repository: oci://registry-1.docker.io/bitnamicharts
