apiVersion: v2
name: stream
description: EverTrust Stream Helm chart
type: application
version: 1.6.6
appVersion: "2.0.8"
icon: https://evertrust.io/media/logo-stream-blue.png
home: https://evertrust.io
sources:
  - https://github.com/evertrust/stream-helm
dependencies:
  - name: common
    version: 2.2.2
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    version: 13.6.2
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
