apiVersion: v2
name: stream
description: EverTrust Stream Helm chart
type: application
version: 0.1.9
appVersion: "1.2.1"
home: https://evertrust.fr
sources:
  - https://gitlab.com/evertrust/stream-helm
dependencies:
  - name: common
    version: 2.2.2
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    version: 13.6.2
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
