apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-internal
  labels: {{- include "stream.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: management
      port: 8558
      protocol: TCP
      targetPort: 8558
    - name: artery
      port: 25520
      protocol: TCP
      targetPort: 25520
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
  clusterIP: None
  publishNotReadyAddresses: true