{{ if .Values.horizontalAutoscaler.enabled | default false }}
apiVersion: {{ include "common.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "stream.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
    kind: Deployment
    name: {{ template "common.names.fullname" . }}
  minReplicas: {{ .Values.horizontalAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.horizontalAutoscaler.maxReplicas }}
  metrics:
    {{- if .Values.horizontalAutoscaler.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizontalAutoscaler.targetCPU }}
    {{- end }}
    {{- if .Values.horizontalAutoscaler.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.horizontalAutoscaler.targetMemory }}
  {{- end }}
  {{ end }}