{{ if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "stream.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - port: kamon
      path: /metrics
      {{- if .Values.monitoring.serviceMonitor.interval }}
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.monitoring.serviceMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.monitoring.serviceMonitor.metricRelabelings "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.relabelings }}
      relabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.monitoring.serviceMonitor.relabelings "context" $) | nindent 8 }}
      {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{ end }}
