{{ if .Values.disruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "horizon.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.disruptionBudget.minAvailable }}
  minAvailable: {{ .Values.disruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.disruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.disruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
  {{ end }}