{{ if .Values.leases.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "common.names.fullname" . }}-lease
rules:
  - apiGroups: ["akka.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "list", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "common.names.fullname" . }}-lease
subjects:
  - kind: User
    name: system:serviceaccount:{{ .Release.Namespace }}:default
roleRef:
  kind: Role
  name: {{ template "common.names.fullname" . }}-lease
  apiGroup: rbac.authorization.k8s.io
{{ end }}