{{/* This role is required to allow Horizon to wait for the MongoDB service to start. */}}
{{/* It allows the default service account in the release namespace to read services in the same namespace. */}}
{{- if .Values.mongodb.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "common.names.fullname" . }}-service-reader
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "common.names.fullname" . }}-default-service-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "common.names.fullname" . }}-service-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
{{- end }}