{{- if eq (include "stream.shouldRunUpgrade" .) "true" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-upgrade-%s" (include "common.names.fullname" $) (randAlphaNum 6 | lower) }}
spec:
  template:
    spec:
      {{- include "common.images.renderPullSecrets" (dict "images" (list .Values.upgrade.image) "context" $) | nindent 6 }}
      serviceAccountName: {{ template "stream.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      containers:
        - name: stream-upgrade
          image: {{ include "common.images.image" (dict "imageRoot" .Values.upgrade.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.upgrade.image.pullPolicy | default "IfNotPresent" | quote }}
          {{- include "common.images.renderPullSecrets" (dict "images" (list .Values.upgrade.image) "context" $) | nindent 10 }}
          args: [
              "-y",
              "-m", "$(MONGODB_URI)",
              {{- if .Values.upgrade.from }}
              "-s", "{{ .Values.upgrade.from }}",
              {{- end }}
              {{- if .Values.upgrade.to }}
              "-t", "{{ .Values.upgrade.to }}",
              {{- end }}
          ]
          resources: {{- toYaml .Values.upgrade.resources | nindent 12 }}
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.secrets.name" (dict "existingSecret" .Values.externalDatabase.secretName "context" $) }}
                  key: {{ include "common.secrets.key" (dict "existingSecret" .Values.externalDatabase.secretKey "key" "mongoUri") }}
      restartPolicy: Never
  backoffLimit: 0
{{- end }}
