{{- if eq (include "horizon.shouldRunUpgrade" .) "true" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-upgrade-%s" (include "common.names.fullname" $) (randAlphaNum 6 | lower) }}
spec:
  template:
    spec:
      containers:
        - name: horizon-upgrade
          image: {{ include "common.images.image" (dict "imageRoot" .Values.upgrade.image "global" .Values) }}
          imagePullPolicy: {{ .Values.upgrade.image.pullPolicy | default "IfNotPresent" | quote }}
          {{- include "common.images.renderPullSecrets" (dict "images" (list .Values.upgrade.image) "context" $) | nindent 5 }}
          args: [
              "-y",
              "-m", "$(MONGODB_URI)",
              "-s", "{{ coalesce .Values.upgrade.from (include "horizon.installedVersion" .) }}",
              "-t", "{{ coalesce .Values.upgrade.to .Chart.AppVersion }}"
          ]
          resources: {{- toYaml .Values.upgrade.resources | nindent 12 }}
          env:
            - name: MONGODB_URI
              {{- include "horizon.mongodbUri" (dict "context" .) | nindent 14 }}
      restartPolicy: Never
  backoffLimit: 0
{{- end }}