{{- if eq (include "stream.shouldRunUpgrade" .) "true" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-upgrade-%s" (include "common.names.fullname" $) (randAlphaNum 6 | lower) }}
  labels: {{- include "stream.labels.standard" . | nindent 4 }}
  {{- if .Values.commonLabels }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      labels: {{- include "stream.labels.standard" . | nindent 8 }}
      {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
      {{- end }}
      {{- if .Values.commonAnnotations }}
      annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
      {{- end }}
    spec:
      {{- include "common.images.renderPullSecrets" (dict "images" (list .Values.upgrade.image) "context" $) | nindent 6 }}
      serviceAccountName: {{ template "stream.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- if .Values.upgrade.nodeSelector }}
      nodeSelector: {{- toYaml .Values.upgrade.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.upgrade.tolerations }}
      tolerations: {{- toYaml .Values.upgrade.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: stream-upgrade
          image: {{ include "common.images.image" (dict "imageRoot" .Values.upgrade.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.upgrade.image.pullPolicy | default "IfNotPresent" | quote }}
          args: [
              "-y",
              "-m", "$(MONGODB_URI)",
              {{- if .Values.upgrade.from }}
              "-s", "{{ .Values.upgrade.from }}",
              {{- end }}
              {{- if .Values.upgrade.to }}
              "-t", "{{ .Values.upgrade.to }}",
              {{- end }}
          ]
          resources: {{- toYaml .Values.upgrade.resources | nindent 12 }}
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.secrets.name" (dict "existingSecret" .Values.externalDatabase.secretName "context" $) }}
                  key: {{ include "common.secrets.key" (dict "existingSecret" .Values.externalDatabase.secretKey "key" "mongoUri") }}
      restartPolicy: Never
  backoffLimit: 0
{{- end }}
